### PR TITLE
Use external section references

### PR DESCRIPTION
**Pull request by cabo**

### CODE REVIEW

**Comment by EskoDijk** [comment]
On my setup, the "make" fails for the new style section refs: e.g.

draft-ietf-core-groupcomm-bis.xml(0): Error: IDREF attribute target references an unknown ID "Section_9_of_RFC7252", at None

is there something that needs updating? ( xml2rfc 3.2.1 / kramdown-rfc2629 1.3.32 / Msys2 toolchain on Windows 10)

**Comment by cabo** [comment]
Are you sure you are actually using that kramdown-rfc version?
Version 1.3.21 of two months ago added the section references.
Maybe you have another version as well that is older.

**Comment by cabo** [comment]
(Oh, and xml2rfc has been 3.5.0 for a while, and the update is worth it.  But that is not the problem you describe.)

**Comment by cabo** [comment]
One reason may be that you are not calling kramdown-rfc with --v3.  The I-d-template makefile does this automatically -- *if* it is up to date.  Maybe you are short a `git submodule update --recursive --remote` (or whatever your preferred incantation is).

**Comment by EskoDijk** [comment]
@cabo Bingo! Thanks for the tip; I saw that the submodule needed to go from "master" to "main" branch and it was way behind. Now it works nicely. We may merge this PR after the I-D submission deadline because my co-author is still on an older toolchain.

**Comment by cabo** [comment]
Great!  I suggested this because it is better for the end product, but also eases the work of a reviewer by being able klick on those section links.

**Comment by marco-tiloca-sics** [comment]
Adopted in branch v-04, see https://github.com/core-wg/groupcomm-bis/commit/76a5ced3f5865c3d7d1e77bf50e72a722a1ddef9

**Pull request closed without merging**
